//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VersionOfficielle.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VersionOfficielle.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ..\Resources\\ImagesRef\\Numbers\B10.bmp;System.Drawing.Bitmap, System.Drawing, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a.
        /// </summary>
        internal static string B10 {
            get {
                return ResourceManager.GetString("B10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ..\Resources\\ImagesRef\\Numbers\B2.bmp;System.Drawing.Bitmap, System.Drawing, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a.
        /// </summary>
        internal static string B2 {
            get {
                return ResourceManager.GetString("B2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ..\Resources\\ImagesRef\\Numbers\B3.bmp;System.Drawing.Bitmap, System.Drawing, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a.
        /// </summary>
        internal static string B3 {
            get {
                return ResourceManager.GetString("B3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ..\Resources\\ImagesRef\\Numbers\B4.bmp;System.Drawing.Bitmap, System.Drawing, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a.
        /// </summary>
        internal static string B4 {
            get {
                return ResourceManager.GetString("B4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ..\Resources\\ImagesRef\\Numbers\B5.bmp;System.Drawing.Bitmap, System.Drawing, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a.
        /// </summary>
        internal static string B5 {
            get {
                return ResourceManager.GetString("B5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ..\Resources\\ImagesRef\\Numbers\B6.bmp;System.Drawing.Bitmap, System.Drawing, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a.
        /// </summary>
        internal static string B6 {
            get {
                return ResourceManager.GetString("B6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ..\Resources\\ImagesRef\\Numbers\B7.bmp;System.Drawing.Bitmap, System.Drawing, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a.
        /// </summary>
        internal static string B7 {
            get {
                return ResourceManager.GetString("B7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ..\Resources\\ImagesRef\\Numbers\B8.bmp;System.Drawing.Bitmap, System.Drawing, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a.
        /// </summary>
        internal static string B8 {
            get {
                return ResourceManager.GetString("B8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ..\Resources\\ImagesRef\\Numbers\B9.bmp;System.Drawing.Bitmap, System.Drawing, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a.
        /// </summary>
        internal static string B9 {
            get {
                return ResourceManager.GetString("B9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ..\Resources\\ImagesRef\\Numbers\BA.bmp;System.Drawing.Bitmap, System.Drawing, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a.
        /// </summary>
        internal static string BA {
            get {
                return ResourceManager.GetString("BA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ..\Resources\\ImagesRef\\Numbers\BJ.bmp;System.Drawing.Bitmap, System.Drawing, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a.
        /// </summary>
        internal static string BJ {
            get {
                return ResourceManager.GetString("BJ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ..\Resources\\ImagesRef\\Numbers\BK.bmp;System.Drawing.Bitmap, System.Drawing, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a.
        /// </summary>
        internal static string BK {
            get {
                return ResourceManager.GetString("BK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ..\Resources\\ImagesRef\\Numbers\BQ.bmp;System.Drawing.Bitmap, System.Drawing, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a.
        /// </summary>
        internal static string BQ {
            get {
                return ResourceManager.GetString("BQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ..\Resources\\ImagesRef\\Numbers\R10.bmp;System.Drawing.Bitmap, System.Drawing, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a.
        /// </summary>
        internal static string R10 {
            get {
                return ResourceManager.GetString("R10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ..\Resources\\ImagesRef\\Numbers\R2.bmp;System.Drawing.Bitmap, System.Drawing, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a.
        /// </summary>
        internal static string R2 {
            get {
                return ResourceManager.GetString("R2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ..\Resources\\ImagesRef\\Numbers\R3.bmp;System.Drawing.Bitmap, System.Drawing, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a.
        /// </summary>
        internal static string R3 {
            get {
                return ResourceManager.GetString("R3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ..\Resources\\ImagesRef\\Numbers\R4.bmp;System.Drawing.Bitmap, System.Drawing, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a.
        /// </summary>
        internal static string R4 {
            get {
                return ResourceManager.GetString("R4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ..\Resources\\ImagesRef\\Numbers\R5.bmp;System.Drawing.Bitmap, System.Drawing, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a.
        /// </summary>
        internal static string R5 {
            get {
                return ResourceManager.GetString("R5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ..\Resources\\ImagesRef\\Numbers\R6.bmp;System.Drawing.Bitmap, System.Drawing, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a.
        /// </summary>
        internal static string R6 {
            get {
                return ResourceManager.GetString("R6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ..\Resources\\ImagesRef\\Numbers\R7.bmp;System.Drawing.Bitmap, System.Drawing, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a.
        /// </summary>
        internal static string R7 {
            get {
                return ResourceManager.GetString("R7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ..\Resources\\ImagesRef\\Numbers\R8.bmp;System.Drawing.Bitmap, System.Drawing, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a.
        /// </summary>
        internal static string R8 {
            get {
                return ResourceManager.GetString("R8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ..\Resources\\ImagesRef\\Numbers\R9.bmp;System.Drawing.Bitmap, System.Drawing, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a.
        /// </summary>
        internal static string R9 {
            get {
                return ResourceManager.GetString("R9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ..\Resources\\ImagesRef\\Numbers\RA.bmp;System.Drawing.Bitmap, System.Drawing, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a.
        /// </summary>
        internal static string RA {
            get {
                return ResourceManager.GetString("RA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ..\Resources\\ImagesRef\\Numbers\RJ.bmp;System.Drawing.Bitmap, System.Drawing, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a.
        /// </summary>
        internal static string RJ {
            get {
                return ResourceManager.GetString("RJ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ..\Resources\\ImagesRef\\Numbers\RK.bmp;System.Drawing.Bitmap, System.Drawing, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a.
        /// </summary>
        internal static string RK {
            get {
                return ResourceManager.GetString("RK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ..\Resources\\ImagesRef\\Numbers\RQ.bmp;System.Drawing.Bitmap, System.Drawing, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a.
        /// </summary>
        internal static string RQ {
            get {
                return ResourceManager.GetString("RQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ..\Resources\Sample0.bmp;System.Drawing.Bitmap, System.Drawing, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a.
        /// </summary>
        internal static string Sample0 {
            get {
                return ResourceManager.GetString("Sample0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ..\Resources\Sample1.bmp;System.Drawing.Bitmap, System.Drawing, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a.
        /// </summary>
        internal static string Sample1 {
            get {
                return ResourceManager.GetString("Sample1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ..\Resources\Sample2.bmp;System.Drawing.Bitmap, System.Drawing, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a.
        /// </summary>
        internal static string Sample2 {
            get {
                return ResourceManager.GetString("Sample2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ..\Resources\Sample3.bmp;System.Drawing.Bitmap, System.Drawing, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a.
        /// </summary>
        internal static string Sample3 {
            get {
                return ResourceManager.GetString("Sample3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ..\Resources\Sample4.bmp;System.Drawing.Bitmap, System.Drawing, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a.
        /// </summary>
        internal static string Sample4 {
            get {
                return ResourceManager.GetString("Sample4", resourceCulture);
            }
        }
    }
}
