//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap LAUNCHER_ESPACEJEUX_FILTERS_CHK_DISABLED {
            get {
                object obj = ResourceManager.GetObject("LAUNCHER_ESPACEJEUX_FILTERS_CHK_DISABLED", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap LAUNCHER_ESPACEJEUX_FILTERS_CHK_ENABLED {
            get {
                object obj = ResourceManager.GetObject("LAUNCHER_ESPACEJEUX_FILTERS_CHK_ENABLED", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap LAUNCHER_ESPACEJEUX_FILTERS_DROP_DOWN_BUTTON_BMP {
            get {
                object obj = ResourceManager.GetObject("LAUNCHER_ESPACEJEUX_FILTERS_DROP_DOWN_BUTTON_BMP", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap LAUNCHER_ESPACEJEUX_FILTERS_TXT_BOX_EMPTY_BMP {
            get {
                object obj = ResourceManager.GetObject("LAUNCHER_ESPACEJEUX_FILTERS_TXT_BOX_EMPTY_BMP", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap LAUNCHER_ESPACEJEUX_FILTERS_VALUE_002_04_BMP {
            get {
                object obj = ResourceManager.GetObject("LAUNCHER_ESPACEJEUX_FILTERS_VALUE_002_04_BMP", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap LAUNCHER_ESPACEJEUX_FILTERS_VALUE_005_01_BMP {
            get {
                object obj = ResourceManager.GetObject("LAUNCHER_ESPACEJEUX_FILTERS_VALUE_005_01_BMP", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap LAUNCHER_ESPACEJEUX_FILTERS_VALUE_01_02_BMP {
            get {
                object obj = ResourceManager.GetObject("LAUNCHER_ESPACEJEUX_FILTERS_VALUE_01_02_BMP", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap LAUNCHER_ESPACEJEUX_FILTERS_VALUE_015_03_BMP {
            get {
                object obj = ResourceManager.GetObject("LAUNCHER_ESPACEJEUX_FILTERS_VALUE_015_03_BMP", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap LAUNCHER_ESPACEJEUX_FILTERS_VALUE_025_05_BMP {
            get {
                object obj = ResourceManager.GetObject("LAUNCHER_ESPACEJEUX_FILTERS_VALUE_025_05_BMP", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap LAUNCHER_ESPACEJEUX_FILTERS_VALUE_05_1_BMP {
            get {
                object obj = ResourceManager.GetObject("LAUNCHER_ESPACEJEUX_FILTERS_VALUE_05_1_BMP", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap LAUNCHER_ESPACEJEUX_FILTERS_VALUE_1_2_BMP {
            get {
                object obj = ResourceManager.GetObject("LAUNCHER_ESPACEJEUX_FILTERS_VALUE_1_2_BMP", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap LAUNCHER_ESPACEJEUX_FILTERS_VALUE_10_20_BMP {
            get {
                object obj = ResourceManager.GetObject("LAUNCHER_ESPACEJEUX_FILTERS_VALUE_10_20_BMP", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap LAUNCHER_ESPACEJEUX_FILTERS_VALUE_15_30_BMP {
            get {
                object obj = ResourceManager.GetObject("LAUNCHER_ESPACEJEUX_FILTERS_VALUE_15_30_BMP", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap LAUNCHER_ESPACEJEUX_FILTERS_VALUE_2_4_BMP {
            get {
                object obj = ResourceManager.GetObject("LAUNCHER_ESPACEJEUX_FILTERS_VALUE_2_4_BMP", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap LAUNCHER_ESPACEJEUX_FILTERS_VALUE_20_40_BMP {
            get {
                object obj = ResourceManager.GetObject("LAUNCHER_ESPACEJEUX_FILTERS_VALUE_20_40_BMP", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap LAUNCHER_ESPACEJEUX_FILTERS_VALUE_25_5_BMP {
            get {
                object obj = ResourceManager.GetObject("LAUNCHER_ESPACEJEUX_FILTERS_VALUE_25_5_BMP", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap LAUNCHER_ESPACEJEUX_FILTERS_VALUE_25_50_BMP {
            get {
                object obj = ResourceManager.GetObject("LAUNCHER_ESPACEJEUX_FILTERS_VALUE_25_50_BMP", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap LAUNCHER_ESPACEJEUX_FILTERS_VALUE_3_6_BMP {
            get {
                object obj = ResourceManager.GetObject("LAUNCHER_ESPACEJEUX_FILTERS_VALUE_3_6_BMP", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap LAUNCHER_ESPACEJEUX_FILTERS_VALUE_4_8_BMP {
            get {
                object obj = ResourceManager.GetObject("LAUNCHER_ESPACEJEUX_FILTERS_VALUE_4_8_BMP", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap LAUNCHER_ESPACEJEUX_FILTERS_VALUE_5_10_BMP {
            get {
                object obj = ResourceManager.GetObject("LAUNCHER_ESPACEJEUX_FILTERS_VALUE_5_10_BMP", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap LAUNCHER_ESPACEJEUX_FILTERS_VALUE_8_16_BMP {
            get {
                object obj = ResourceManager.GetObject("LAUNCHER_ESPACEJEUX_FILTERS_VALUE_8_16_BMP", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap LAUNCHER_ESPACEJEUX_FILTERS_VALUE_NONE_BMP {
            get {
                object obj = ResourceManager.GetObject("LAUNCHER_ESPACEJEUX_FILTERS_VALUE_NONE_BMP", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap LAUNCHER_ESPACEJEUX_POPUP_CIRCLE_EXCLAMATION_BMP {
            get {
                object obj = ResourceManager.GetObject("LAUNCHER_ESPACEJEUX_POPUP_CIRCLE_EXCLAMATION_BMP", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap LAUNCHER_ESPACEJEUX_POPUP_CIRCLE_EXCLAMATION_BMP2 {
            get {
                object obj = ResourceManager.GetObject("LAUNCHER_ESPACEJEUX_POPUP_CIRCLE_EXCLAMATION_BMP2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap LAUNCHER_ESPACEJEUX_POPUP_CIRCLE_QUESTION_BMP {
            get {
                object obj = ResourceManager.GetObject("LAUNCHER_ESPACEJEUX_POPUP_CIRCLE_QUESTION_BMP", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap LAUNCHER_ESPACEJEUX_TABLEGRID_EMPTY_ROW_1 {
            get {
                object obj = ResourceManager.GetObject("LAUNCHER_ESPACEJEUX_TABLEGRID_EMPTY_ROW_1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap LAUNCHER_ESPACEJEUX_TABLEGRID_EMPTY_ROW_2 {
            get {
                object obj = ResourceManager.GetObject("LAUNCHER_ESPACEJEUX_TABLEGRID_EMPTY_ROW_2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap LAUNCHER_ESPACEJEUX_TABLEGRID_PLRS_0_2_BMP1 {
            get {
                object obj = ResourceManager.GetObject("LAUNCHER_ESPACEJEUX_TABLEGRID_PLRS_0_2_BMP1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap LAUNCHER_ESPACEJEUX_TABLEGRID_PLRS_2_2_BMP {
            get {
                object obj = ResourceManager.GetObject("LAUNCHER_ESPACEJEUX_TABLEGRID_PLRS_2_2_BMP", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap LAUNCHER_ESPACEJEUX_TABLEGRID_PLRS_2_2_BMP2 {
            get {
                object obj = ResourceManager.GetObject("LAUNCHER_ESPACEJEUX_TABLEGRID_PLRS_2_2_BMP2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap LAUNCHER_ESPACEJEUX_TABLEGRID_PLRS_2_2_BMP3 {
            get {
                object obj = ResourceManager.GetObject("LAUNCHER_ESPACEJEUX_TABLEGRID_PLRS_2_2_BMP3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap LAUNCHER_ESPACEJEUX_TABLEGRID_PLRS_SORTING_DECREMENTING_BMP {
            get {
                object obj = ResourceManager.GetObject("LAUNCHER_ESPACEJEUX_TABLEGRID_PLRS_SORTING_DECREMENTING_BMP", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap LAUNCHER_ESPACEJEUX_TABLEGRID_TABLENAME_CHARACTER_0_BMP1 {
            get {
                object obj = ResourceManager.GetObject("LAUNCHER_ESPACEJEUX_TABLEGRID_TABLENAME_CHARACTER_0_BMP1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap LAUNCHER_ESPACEJEUX_TABLEGRID_TABLENAME_CHARACTER_0_BMP2 {
            get {
                object obj = ResourceManager.GetObject("LAUNCHER_ESPACEJEUX_TABLEGRID_TABLENAME_CHARACTER_0_BMP2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap LAUNCHER_ESPACEJEUX_TABLEGRID_TABLENAME_CHARACTER_0_BMP3 {
            get {
                object obj = ResourceManager.GetObject("LAUNCHER_ESPACEJEUX_TABLEGRID_TABLENAME_CHARACTER_0_BMP3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap LAUNCHER_ESPACEJEUX_TABLEGRID_TABLENAME_CHARACTER_1_BMP1 {
            get {
                object obj = ResourceManager.GetObject("LAUNCHER_ESPACEJEUX_TABLEGRID_TABLENAME_CHARACTER_1_BMP1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap LAUNCHER_ESPACEJEUX_TABLEGRID_TABLENAME_CHARACTER_1_BMP2 {
            get {
                object obj = ResourceManager.GetObject("LAUNCHER_ESPACEJEUX_TABLEGRID_TABLENAME_CHARACTER_1_BMP2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap LAUNCHER_ESPACEJEUX_TABLEGRID_TABLENAME_CHARACTER_1_BMP3 {
            get {
                object obj = ResourceManager.GetObject("LAUNCHER_ESPACEJEUX_TABLEGRID_TABLENAME_CHARACTER_1_BMP3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap LAUNCHER_ESPACEJEUX_TABLEGRID_TABLENAME_CHARACTER_2_BMP1 {
            get {
                object obj = ResourceManager.GetObject("LAUNCHER_ESPACEJEUX_TABLEGRID_TABLENAME_CHARACTER_2_BMP1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap LAUNCHER_ESPACEJEUX_TABLEGRID_TABLENAME_CHARACTER_2_BMP2 {
            get {
                object obj = ResourceManager.GetObject("LAUNCHER_ESPACEJEUX_TABLEGRID_TABLENAME_CHARACTER_2_BMP2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap LAUNCHER_ESPACEJEUX_TABLEGRID_TABLENAME_CHARACTER_2_BMP3 {
            get {
                object obj = ResourceManager.GetObject("LAUNCHER_ESPACEJEUX_TABLEGRID_TABLENAME_CHARACTER_2_BMP3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap LAUNCHER_ESPACEJEUX_TABLEGRID_TABLENAME_CHARACTER_3_BMP1 {
            get {
                object obj = ResourceManager.GetObject("LAUNCHER_ESPACEJEUX_TABLEGRID_TABLENAME_CHARACTER_3_BMP1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap LAUNCHER_ESPACEJEUX_TABLEGRID_TABLENAME_CHARACTER_3_BMP2 {
            get {
                object obj = ResourceManager.GetObject("LAUNCHER_ESPACEJEUX_TABLEGRID_TABLENAME_CHARACTER_3_BMP2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap LAUNCHER_ESPACEJEUX_TABLEGRID_TABLENAME_CHARACTER_3_BMP3 {
            get {
                object obj = ResourceManager.GetObject("LAUNCHER_ESPACEJEUX_TABLEGRID_TABLENAME_CHARACTER_3_BMP3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap LAUNCHER_ESPACEJEUX_TABLEGRID_TABLENAME_CHARACTER_4_BMP1 {
            get {
                object obj = ResourceManager.GetObject("LAUNCHER_ESPACEJEUX_TABLEGRID_TABLENAME_CHARACTER_4_BMP1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap LAUNCHER_ESPACEJEUX_TABLEGRID_TABLENAME_CHARACTER_4_BMP2 {
            get {
                object obj = ResourceManager.GetObject("LAUNCHER_ESPACEJEUX_TABLEGRID_TABLENAME_CHARACTER_4_BMP2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap LAUNCHER_ESPACEJEUX_TABLEGRID_TABLENAME_CHARACTER_4_BMP3 {
            get {
                object obj = ResourceManager.GetObject("LAUNCHER_ESPACEJEUX_TABLEGRID_TABLENAME_CHARACTER_4_BMP3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap LAUNCHER_ESPACEJEUX_TABLEGRID_TABLENAME_CHARACTER_5_BMP1 {
            get {
                object obj = ResourceManager.GetObject("LAUNCHER_ESPACEJEUX_TABLEGRID_TABLENAME_CHARACTER_5_BMP1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap LAUNCHER_ESPACEJEUX_TABLEGRID_TABLENAME_CHARACTER_5_BMP2 {
            get {
                object obj = ResourceManager.GetObject("LAUNCHER_ESPACEJEUX_TABLEGRID_TABLENAME_CHARACTER_5_BMP2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap LAUNCHER_ESPACEJEUX_TABLEGRID_TABLENAME_CHARACTER_5_BMP3 {
            get {
                object obj = ResourceManager.GetObject("LAUNCHER_ESPACEJEUX_TABLEGRID_TABLENAME_CHARACTER_5_BMP3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap LAUNCHER_ESPACEJEUX_TABLEGRID_TABLENAME_CHARACTER_6_BMP1 {
            get {
                object obj = ResourceManager.GetObject("LAUNCHER_ESPACEJEUX_TABLEGRID_TABLENAME_CHARACTER_6_BMP1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap LAUNCHER_ESPACEJEUX_TABLEGRID_TABLENAME_CHARACTER_6_BMP2 {
            get {
                object obj = ResourceManager.GetObject("LAUNCHER_ESPACEJEUX_TABLEGRID_TABLENAME_CHARACTER_6_BMP2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap LAUNCHER_ESPACEJEUX_TABLEGRID_TABLENAME_CHARACTER_6_BMP3 {
            get {
                object obj = ResourceManager.GetObject("LAUNCHER_ESPACEJEUX_TABLEGRID_TABLENAME_CHARACTER_6_BMP3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap LAUNCHER_ESPACEJEUX_TABLEGRID_TABLENAME_CHARACTER_7_BMP1 {
            get {
                object obj = ResourceManager.GetObject("LAUNCHER_ESPACEJEUX_TABLEGRID_TABLENAME_CHARACTER_7_BMP1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap LAUNCHER_ESPACEJEUX_TABLEGRID_TABLENAME_CHARACTER_7_BMP2 {
            get {
                object obj = ResourceManager.GetObject("LAUNCHER_ESPACEJEUX_TABLEGRID_TABLENAME_CHARACTER_7_BMP2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap LAUNCHER_ESPACEJEUX_TABLEGRID_TABLENAME_CHARACTER_7_BMP3 {
            get {
                object obj = ResourceManager.GetObject("LAUNCHER_ESPACEJEUX_TABLEGRID_TABLENAME_CHARACTER_7_BMP3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap LAUNCHER_ESPACEJEUX_TABLEGRID_TABLENAME_CHARACTER_8_BMP1 {
            get {
                object obj = ResourceManager.GetObject("LAUNCHER_ESPACEJEUX_TABLEGRID_TABLENAME_CHARACTER_8_BMP1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap LAUNCHER_ESPACEJEUX_TABLEGRID_TABLENAME_CHARACTER_8_BMP2 {
            get {
                object obj = ResourceManager.GetObject("LAUNCHER_ESPACEJEUX_TABLEGRID_TABLENAME_CHARACTER_8_BMP2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap LAUNCHER_ESPACEJEUX_TABLEGRID_TABLENAME_CHARACTER_8_BMP3 {
            get {
                object obj = ResourceManager.GetObject("LAUNCHER_ESPACEJEUX_TABLEGRID_TABLENAME_CHARACTER_8_BMP3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap LAUNCHER_ESPACEJEUX_TABLEGRID_TABLENAME_CHARACTER_9_BMP1 {
            get {
                object obj = ResourceManager.GetObject("LAUNCHER_ESPACEJEUX_TABLEGRID_TABLENAME_CHARACTER_9_BMP1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap LAUNCHER_ESPACEJEUX_TABLEGRID_TABLENAME_CHARACTER_9_BMP2 {
            get {
                object obj = ResourceManager.GetObject("LAUNCHER_ESPACEJEUX_TABLEGRID_TABLENAME_CHARACTER_9_BMP2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap LAUNCHER_ESPACEJEUX_TABLEGRID_TABLENAME_CHARACTER_9_BMP3 {
            get {
                object obj = ResourceManager.GetObject("LAUNCHER_ESPACEJEUX_TABLEGRID_TABLENAME_CHARACTER_9_BMP3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap TWOMAX_ESPACEJEUX_BOARD_TYPE_CLUB_BMP {
            get {
                object obj = ResourceManager.GetObject("TWOMAX_ESPACEJEUX_BOARD_TYPE_CLUB_BMP", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap TWOMAX_ESPACEJEUX_BOARD_TYPE_CLUB2_BMP {
            get {
                object obj = ResourceManager.GetObject("TWOMAX_ESPACEJEUX_BOARD_TYPE_CLUB2_BMP", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap TWOMAX_ESPACEJEUX_BOARD_TYPE_DIAMOND_BMP {
            get {
                object obj = ResourceManager.GetObject("TWOMAX_ESPACEJEUX_BOARD_TYPE_DIAMOND_BMP", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap TWOMAX_ESPACEJEUX_BOARD_TYPE_DIAMOND2_BMP {
            get {
                object obj = ResourceManager.GetObject("TWOMAX_ESPACEJEUX_BOARD_TYPE_DIAMOND2_BMP", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap TWOMAX_ESPACEJEUX_BOARD_TYPE_HEART_BMP {
            get {
                object obj = ResourceManager.GetObject("TWOMAX_ESPACEJEUX_BOARD_TYPE_HEART_BMP", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap TWOMAX_ESPACEJEUX_BOARD_TYPE_HEART2_BMP {
            get {
                object obj = ResourceManager.GetObject("TWOMAX_ESPACEJEUX_BOARD_TYPE_HEART2_BMP", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap TWOMAX_ESPACEJEUX_BOARD_TYPE_SPADE_BMP {
            get {
                object obj = ResourceManager.GetObject("TWOMAX_ESPACEJEUX_BOARD_TYPE_SPADE_BMP", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap TWOMAX_ESPACEJEUX_BOARD_TYPE_SPADE2_BMP {
            get {
                object obj = ResourceManager.GetObject("TWOMAX_ESPACEJEUX_BOARD_TYPE_SPADE2_BMP", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap TWOMAX_ESPACEJEUX_BOARD_TYPE_SPADE3_BMP {
            get {
                object obj = ResourceManager.GetObject("TWOMAX_ESPACEJEUX_BOARD_TYPE_SPADE3_BMP", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap TWOMAX_ESPACEJEUX_BOARD_VALUE_ACE_BLACK_BMP {
            get {
                object obj = ResourceManager.GetObject("TWOMAX_ESPACEJEUX_BOARD_VALUE_ACE_BLACK_BMP", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap TWOMAX_ESPACEJEUX_BOARD_VALUE_ACE_BLACK2_BMP {
            get {
                object obj = ResourceManager.GetObject("TWOMAX_ESPACEJEUX_BOARD_VALUE_ACE_BLACK2_BMP", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap TWOMAX_ESPACEJEUX_BOARD_VALUE_ACE_RED_BMP {
            get {
                object obj = ResourceManager.GetObject("TWOMAX_ESPACEJEUX_BOARD_VALUE_ACE_RED_BMP", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap TWOMAX_ESPACEJEUX_BOARD_VALUE_ACE_RED2_BMP {
            get {
                object obj = ResourceManager.GetObject("TWOMAX_ESPACEJEUX_BOARD_VALUE_ACE_RED2_BMP", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap TWOMAX_ESPACEJEUX_BOARD_VALUE_ACE_RED3_BMP {
            get {
                object obj = ResourceManager.GetObject("TWOMAX_ESPACEJEUX_BOARD_VALUE_ACE_RED3_BMP", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap TWOMAX_ESPACEJEUX_BOARD_VALUE_EIGHT_BLACK_BMP {
            get {
                object obj = ResourceManager.GetObject("TWOMAX_ESPACEJEUX_BOARD_VALUE_EIGHT_BLACK_BMP", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap TWOMAX_ESPACEJEUX_BOARD_VALUE_EIGHT_BLACK2_BMP {
            get {
                object obj = ResourceManager.GetObject("TWOMAX_ESPACEJEUX_BOARD_VALUE_EIGHT_BLACK2_BMP", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap TWOMAX_ESPACEJEUX_BOARD_VALUE_EIGHT_RED_BMP {
            get {
                object obj = ResourceManager.GetObject("TWOMAX_ESPACEJEUX_BOARD_VALUE_EIGHT_RED_BMP", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap TWOMAX_ESPACEJEUX_BOARD_VALUE_EIGHT_RED2_BMP {
            get {
                object obj = ResourceManager.GetObject("TWOMAX_ESPACEJEUX_BOARD_VALUE_EIGHT_RED2_BMP", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap TWOMAX_ESPACEJEUX_BOARD_VALUE_FIVE_BLACK_BMP {
            get {
                object obj = ResourceManager.GetObject("TWOMAX_ESPACEJEUX_BOARD_VALUE_FIVE_BLACK_BMP", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap TWOMAX_ESPACEJEUX_BOARD_VALUE_FIVE_BLACK2_BMP {
            get {
                object obj = ResourceManager.GetObject("TWOMAX_ESPACEJEUX_BOARD_VALUE_FIVE_BLACK2_BMP", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap TWOMAX_ESPACEJEUX_BOARD_VALUE_FIVE_RED_BMP {
            get {
                object obj = ResourceManager.GetObject("TWOMAX_ESPACEJEUX_BOARD_VALUE_FIVE_RED_BMP", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap TWOMAX_ESPACEJEUX_BOARD_VALUE_FIVE_RED2_BMP {
            get {
                object obj = ResourceManager.GetObject("TWOMAX_ESPACEJEUX_BOARD_VALUE_FIVE_RED2_BMP", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap TWOMAX_ESPACEJEUX_BOARD_VALUE_FOUR_BLACK_BMP {
            get {
                object obj = ResourceManager.GetObject("TWOMAX_ESPACEJEUX_BOARD_VALUE_FOUR_BLACK_BMP", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap TWOMAX_ESPACEJEUX_BOARD_VALUE_FOUR_BLACK2_BMP {
            get {
                object obj = ResourceManager.GetObject("TWOMAX_ESPACEJEUX_BOARD_VALUE_FOUR_BLACK2_BMP", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap TWOMAX_ESPACEJEUX_BOARD_VALUE_FOUR_RED_BMP {
            get {
                object obj = ResourceManager.GetObject("TWOMAX_ESPACEJEUX_BOARD_VALUE_FOUR_RED_BMP", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap TWOMAX_ESPACEJEUX_BOARD_VALUE_FOUR_RED2_BMP {
            get {
                object obj = ResourceManager.GetObject("TWOMAX_ESPACEJEUX_BOARD_VALUE_FOUR_RED2_BMP", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap TWOMAX_ESPACEJEUX_BOARD_VALUE_JACK_BLACK_BMP {
            get {
                object obj = ResourceManager.GetObject("TWOMAX_ESPACEJEUX_BOARD_VALUE_JACK_BLACK_BMP", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap TWOMAX_ESPACEJEUX_BOARD_VALUE_JACK_BLACK2_BMP {
            get {
                object obj = ResourceManager.GetObject("TWOMAX_ESPACEJEUX_BOARD_VALUE_JACK_BLACK2_BMP", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap TWOMAX_ESPACEJEUX_BOARD_VALUE_JACK_RED_BMP {
            get {
                object obj = ResourceManager.GetObject("TWOMAX_ESPACEJEUX_BOARD_VALUE_JACK_RED_BMP", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap TWOMAX_ESPACEJEUX_BOARD_VALUE_JACK_RED2_BMP {
            get {
                object obj = ResourceManager.GetObject("TWOMAX_ESPACEJEUX_BOARD_VALUE_JACK_RED2_BMP", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap TWOMAX_ESPACEJEUX_BOARD_VALUE_KING_BLACK_BMP {
            get {
                object obj = ResourceManager.GetObject("TWOMAX_ESPACEJEUX_BOARD_VALUE_KING_BLACK_BMP", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap TWOMAX_ESPACEJEUX_BOARD_VALUE_KING_BLACK2_BMP {
            get {
                object obj = ResourceManager.GetObject("TWOMAX_ESPACEJEUX_BOARD_VALUE_KING_BLACK2_BMP", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap TWOMAX_ESPACEJEUX_BOARD_VALUE_KING_BLACK3_BMP {
            get {
                object obj = ResourceManager.GetObject("TWOMAX_ESPACEJEUX_BOARD_VALUE_KING_BLACK3_BMP", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap TWOMAX_ESPACEJEUX_BOARD_VALUE_KING_RED_BMP {
            get {
                object obj = ResourceManager.GetObject("TWOMAX_ESPACEJEUX_BOARD_VALUE_KING_RED_BMP", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap TWOMAX_ESPACEJEUX_BOARD_VALUE_KING_RED2_BMP {
            get {
                object obj = ResourceManager.GetObject("TWOMAX_ESPACEJEUX_BOARD_VALUE_KING_RED2_BMP", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap TWOMAX_ESPACEJEUX_BOARD_VALUE_NINE_BLACK_BMP {
            get {
                object obj = ResourceManager.GetObject("TWOMAX_ESPACEJEUX_BOARD_VALUE_NINE_BLACK_BMP", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap TWOMAX_ESPACEJEUX_BOARD_VALUE_NINE_BLACK2_BMP {
            get {
                object obj = ResourceManager.GetObject("TWOMAX_ESPACEJEUX_BOARD_VALUE_NINE_BLACK2_BMP", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap TWOMAX_ESPACEJEUX_BOARD_VALUE_NINE_RED_BMP {
            get {
                object obj = ResourceManager.GetObject("TWOMAX_ESPACEJEUX_BOARD_VALUE_NINE_RED_BMP", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap TWOMAX_ESPACEJEUX_BOARD_VALUE_NINE_RED2_BMP {
            get {
                object obj = ResourceManager.GetObject("TWOMAX_ESPACEJEUX_BOARD_VALUE_NINE_RED2_BMP", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap TWOMAX_ESPACEJEUX_BOARD_VALUE_QUEEN_BLACK_BMP {
            get {
                object obj = ResourceManager.GetObject("TWOMAX_ESPACEJEUX_BOARD_VALUE_QUEEN_BLACK_BMP", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap TWOMAX_ESPACEJEUX_BOARD_VALUE_QUEEN_BLACK2_BMP {
            get {
                object obj = ResourceManager.GetObject("TWOMAX_ESPACEJEUX_BOARD_VALUE_QUEEN_BLACK2_BMP", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap TWOMAX_ESPACEJEUX_BOARD_VALUE_QUEEN_RED_BMP {
            get {
                object obj = ResourceManager.GetObject("TWOMAX_ESPACEJEUX_BOARD_VALUE_QUEEN_RED_BMP", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap TWOMAX_ESPACEJEUX_BOARD_VALUE_QUEEN_RED2_BMP {
            get {
                object obj = ResourceManager.GetObject("TWOMAX_ESPACEJEUX_BOARD_VALUE_QUEEN_RED2_BMP", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap TWOMAX_ESPACEJEUX_BOARD_VALUE_SEVEN_BLACK_BMP {
            get {
                object obj = ResourceManager.GetObject("TWOMAX_ESPACEJEUX_BOARD_VALUE_SEVEN_BLACK_BMP", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap TWOMAX_ESPACEJEUX_BOARD_VALUE_SEVEN_BLACK2_BMP {
            get {
                object obj = ResourceManager.GetObject("TWOMAX_ESPACEJEUX_BOARD_VALUE_SEVEN_BLACK2_BMP", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap TWOMAX_ESPACEJEUX_BOARD_VALUE_SEVEN_RED_BMP {
            get {
                object obj = ResourceManager.GetObject("TWOMAX_ESPACEJEUX_BOARD_VALUE_SEVEN_RED_BMP", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap TWOMAX_ESPACEJEUX_BOARD_VALUE_SIX_BLACK_BMP {
            get {
                object obj = ResourceManager.GetObject("TWOMAX_ESPACEJEUX_BOARD_VALUE_SIX_BLACK_BMP", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap TWOMAX_ESPACEJEUX_BOARD_VALUE_SIX_BLACK2_BMP {
            get {
                object obj = ResourceManager.GetObject("TWOMAX_ESPACEJEUX_BOARD_VALUE_SIX_BLACK2_BMP", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap TWOMAX_ESPACEJEUX_BOARD_VALUE_SIX_RED_BMP {
            get {
                object obj = ResourceManager.GetObject("TWOMAX_ESPACEJEUX_BOARD_VALUE_SIX_RED_BMP", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap TWOMAX_ESPACEJEUX_BOARD_VALUE_SIX_RED2_BMP {
            get {
                object obj = ResourceManager.GetObject("TWOMAX_ESPACEJEUX_BOARD_VALUE_SIX_RED2_BMP", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap TWOMAX_ESPACEJEUX_BOARD_VALUE_TEN_BLACK_BMP {
            get {
                object obj = ResourceManager.GetObject("TWOMAX_ESPACEJEUX_BOARD_VALUE_TEN_BLACK_BMP", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap TWOMAX_ESPACEJEUX_BOARD_VALUE_TEN_BLACK2_BMP {
            get {
                object obj = ResourceManager.GetObject("TWOMAX_ESPACEJEUX_BOARD_VALUE_TEN_BLACK2_BMP", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap TWOMAX_ESPACEJEUX_BOARD_VALUE_TEN_BLACK3_BMP {
            get {
                object obj = ResourceManager.GetObject("TWOMAX_ESPACEJEUX_BOARD_VALUE_TEN_BLACK3_BMP", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap TWOMAX_ESPACEJEUX_BOARD_VALUE_TEN_RED_BMP {
            get {
                object obj = ResourceManager.GetObject("TWOMAX_ESPACEJEUX_BOARD_VALUE_TEN_RED_BMP", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap TWOMAX_ESPACEJEUX_BOARD_VALUE_TEN_RED2_BMP {
            get {
                object obj = ResourceManager.GetObject("TWOMAX_ESPACEJEUX_BOARD_VALUE_TEN_RED2_BMP", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap TWOMAX_ESPACEJEUX_BOARD_VALUE_TEN_RED3_BMP {
            get {
                object obj = ResourceManager.GetObject("TWOMAX_ESPACEJEUX_BOARD_VALUE_TEN_RED3_BMP", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap TWOMAX_ESPACEJEUX_BOARD_VALUE_THREE_BLACK_BMP {
            get {
                object obj = ResourceManager.GetObject("TWOMAX_ESPACEJEUX_BOARD_VALUE_THREE_BLACK_BMP", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap TWOMAX_ESPACEJEUX_BOARD_VALUE_THREE_BLACK2_BMP {
            get {
                object obj = ResourceManager.GetObject("TWOMAX_ESPACEJEUX_BOARD_VALUE_THREE_BLACK2_BMP", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap TWOMAX_ESPACEJEUX_BOARD_VALUE_THREE_BLACK3_BMP {
            get {
                object obj = ResourceManager.GetObject("TWOMAX_ESPACEJEUX_BOARD_VALUE_THREE_BLACK3_BMP", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap TWOMAX_ESPACEJEUX_BOARD_VALUE_THREE_RED_BMP {
            get {
                object obj = ResourceManager.GetObject("TWOMAX_ESPACEJEUX_BOARD_VALUE_THREE_RED_BMP", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap TWOMAX_ESPACEJEUX_BOARD_VALUE_THREE_RED2_BMP {
            get {
                object obj = ResourceManager.GetObject("TWOMAX_ESPACEJEUX_BOARD_VALUE_THREE_RED2_BMP", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap TWOMAX_ESPACEJEUX_BOARD_VALUE_TWO_BLACK_BMP {
            get {
                object obj = ResourceManager.GetObject("TWOMAX_ESPACEJEUX_BOARD_VALUE_TWO_BLACK_BMP", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap TWOMAX_ESPACEJEUX_BOARD_VALUE_TWO_BLACK2_BMP {
            get {
                object obj = ResourceManager.GetObject("TWOMAX_ESPACEJEUX_BOARD_VALUE_TWO_BLACK2_BMP", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap TWOMAX_ESPACEJEUX_BOARD_VALUE_TWO_RED_BMP {
            get {
                object obj = ResourceManager.GetObject("TWOMAX_ESPACEJEUX_BOARD_VALUE_TWO_RED_BMP", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap TWOMAX_ESPACEJEUX_BOARD_VALUE_TWO_RED2_BMP {
            get {
                object obj = ResourceManager.GetObject("TWOMAX_ESPACEJEUX_BOARD_VALUE_TWO_RED2_BMP", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap TWOMAX_ESPACEJEUX_BUTTON_ALLIN_BMP {
            get {
                object obj = ResourceManager.GetObject("TWOMAX_ESPACEJEUX_BUTTON_ALLIN_BMP", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap TWOMAX_ESPACEJEUX_BUTTON_CHECK_BMP {
            get {
                object obj = ResourceManager.GetObject("TWOMAX_ESPACEJEUX_BUTTON_CHECK_BMP", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap TWOMAX_ESPACEJEUX_BUTTON_FOLD_BMP {
            get {
                object obj = ResourceManager.GetObject("TWOMAX_ESPACEJEUX_BUTTON_FOLD_BMP", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap TWOMAX_ESPACEJEUX_BUTTON_RAISE_BMP {
            get {
                object obj = ResourceManager.GetObject("TWOMAX_ESPACEJEUX_BUTTON_RAISE_BMP", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap TWOMAX_ESPACEJEUX_HAND_TYPE_CLUB_BMP {
            get {
                object obj = ResourceManager.GetObject("TWOMAX_ESPACEJEUX_HAND_TYPE_CLUB_BMP", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap TWOMAX_ESPACEJEUX_HAND_TYPE_DIAMOND_BMP {
            get {
                object obj = ResourceManager.GetObject("TWOMAX_ESPACEJEUX_HAND_TYPE_DIAMOND_BMP", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap TWOMAX_ESPACEJEUX_HAND_TYPE_HEART_BMP {
            get {
                object obj = ResourceManager.GetObject("TWOMAX_ESPACEJEUX_HAND_TYPE_HEART_BMP", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap TWOMAX_ESPACEJEUX_HAND_TYPE_SPADE_BMP {
            get {
                object obj = ResourceManager.GetObject("TWOMAX_ESPACEJEUX_HAND_TYPE_SPADE_BMP", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap TWOMAX_ESPACEJEUX_HAND_VALUE_ACE_BLACK_BMP {
            get {
                object obj = ResourceManager.GetObject("TWOMAX_ESPACEJEUX_HAND_VALUE_ACE_BLACK_BMP", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap TWOMAX_ESPACEJEUX_HAND_VALUE_ACE_RED_BMP {
            get {
                object obj = ResourceManager.GetObject("TWOMAX_ESPACEJEUX_HAND_VALUE_ACE_RED_BMP", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap TWOMAX_ESPACEJEUX_HAND_VALUE_EIGHT_BLACK_BMP {
            get {
                object obj = ResourceManager.GetObject("TWOMAX_ESPACEJEUX_HAND_VALUE_EIGHT_BLACK_BMP", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap TWOMAX_ESPACEJEUX_HAND_VALUE_EIGHT_RED_BMP {
            get {
                object obj = ResourceManager.GetObject("TWOMAX_ESPACEJEUX_HAND_VALUE_EIGHT_RED_BMP", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap TWOMAX_ESPACEJEUX_HAND_VALUE_FIVE_BLACK_BMP {
            get {
                object obj = ResourceManager.GetObject("TWOMAX_ESPACEJEUX_HAND_VALUE_FIVE_BLACK_BMP", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap TWOMAX_ESPACEJEUX_HAND_VALUE_FIVE_RED_BMP {
            get {
                object obj = ResourceManager.GetObject("TWOMAX_ESPACEJEUX_HAND_VALUE_FIVE_RED_BMP", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap TWOMAX_ESPACEJEUX_HAND_VALUE_FOUR_BLACK_BMP {
            get {
                object obj = ResourceManager.GetObject("TWOMAX_ESPACEJEUX_HAND_VALUE_FOUR_BLACK_BMP", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap TWOMAX_ESPACEJEUX_HAND_VALUE_FOUR_RED_BMP {
            get {
                object obj = ResourceManager.GetObject("TWOMAX_ESPACEJEUX_HAND_VALUE_FOUR_RED_BMP", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap TWOMAX_ESPACEJEUX_HAND_VALUE_JACK_BLACK_BMP {
            get {
                object obj = ResourceManager.GetObject("TWOMAX_ESPACEJEUX_HAND_VALUE_JACK_BLACK_BMP", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap TWOMAX_ESPACEJEUX_HAND_VALUE_JACK_RED_BMP {
            get {
                object obj = ResourceManager.GetObject("TWOMAX_ESPACEJEUX_HAND_VALUE_JACK_RED_BMP", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap TWOMAX_ESPACEJEUX_HAND_VALUE_KING_BLACK_BMP {
            get {
                object obj = ResourceManager.GetObject("TWOMAX_ESPACEJEUX_HAND_VALUE_KING_BLACK_BMP", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap TWOMAX_ESPACEJEUX_HAND_VALUE_KING_BLACK2_BMP {
            get {
                object obj = ResourceManager.GetObject("TWOMAX_ESPACEJEUX_HAND_VALUE_KING_BLACK2_BMP", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap TWOMAX_ESPACEJEUX_HAND_VALUE_KING_RED_BMP {
            get {
                object obj = ResourceManager.GetObject("TWOMAX_ESPACEJEUX_HAND_VALUE_KING_RED_BMP", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap TWOMAX_ESPACEJEUX_HAND_VALUE_KING_RED2_BMP {
            get {
                object obj = ResourceManager.GetObject("TWOMAX_ESPACEJEUX_HAND_VALUE_KING_RED2_BMP", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap TWOMAX_ESPACEJEUX_HAND_VALUE_NINE_BLACK_BMP {
            get {
                object obj = ResourceManager.GetObject("TWOMAX_ESPACEJEUX_HAND_VALUE_NINE_BLACK_BMP", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap TWOMAX_ESPACEJEUX_HAND_VALUE_NINE_RED_BMP {
            get {
                object obj = ResourceManager.GetObject("TWOMAX_ESPACEJEUX_HAND_VALUE_NINE_RED_BMP", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap TWOMAX_ESPACEJEUX_HAND_VALUE_QUEEN_BLACK_BMP {
            get {
                object obj = ResourceManager.GetObject("TWOMAX_ESPACEJEUX_HAND_VALUE_QUEEN_BLACK_BMP", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap TWOMAX_ESPACEJEUX_HAND_VALUE_QUEEN_BLACK2_BMP {
            get {
                object obj = ResourceManager.GetObject("TWOMAX_ESPACEJEUX_HAND_VALUE_QUEEN_BLACK2_BMP", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap TWOMAX_ESPACEJEUX_HAND_VALUE_QUEEN_RED_BMP {
            get {
                object obj = ResourceManager.GetObject("TWOMAX_ESPACEJEUX_HAND_VALUE_QUEEN_RED_BMP", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap TWOMAX_ESPACEJEUX_HAND_VALUE_SEVEN_BLACK_BMP {
            get {
                object obj = ResourceManager.GetObject("TWOMAX_ESPACEJEUX_HAND_VALUE_SEVEN_BLACK_BMP", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap TWOMAX_ESPACEJEUX_HAND_VALUE_SEVEN_RED_BMP {
            get {
                object obj = ResourceManager.GetObject("TWOMAX_ESPACEJEUX_HAND_VALUE_SEVEN_RED_BMP", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap TWOMAX_ESPACEJEUX_HAND_VALUE_SIX_BLACK_BMP {
            get {
                object obj = ResourceManager.GetObject("TWOMAX_ESPACEJEUX_HAND_VALUE_SIX_BLACK_BMP", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap TWOMAX_ESPACEJEUX_HAND_VALUE_SIX_RED_BMP {
            get {
                object obj = ResourceManager.GetObject("TWOMAX_ESPACEJEUX_HAND_VALUE_SIX_RED_BMP", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap TWOMAX_ESPACEJEUX_HAND_VALUE_TEN_BLACK_BMP {
            get {
                object obj = ResourceManager.GetObject("TWOMAX_ESPACEJEUX_HAND_VALUE_TEN_BLACK_BMP", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap TWOMAX_ESPACEJEUX_HAND_VALUE_TEN_BLACK2_BMP {
            get {
                object obj = ResourceManager.GetObject("TWOMAX_ESPACEJEUX_HAND_VALUE_TEN_BLACK2_BMP", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap TWOMAX_ESPACEJEUX_HAND_VALUE_TEN_RED_BMP {
            get {
                object obj = ResourceManager.GetObject("TWOMAX_ESPACEJEUX_HAND_VALUE_TEN_RED_BMP", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap TWOMAX_ESPACEJEUX_HAND_VALUE_THREE_BLACK_BMP {
            get {
                object obj = ResourceManager.GetObject("TWOMAX_ESPACEJEUX_HAND_VALUE_THREE_BLACK_BMP", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap TWOMAX_ESPACEJEUX_HAND_VALUE_THREE_RED_BMP {
            get {
                object obj = ResourceManager.GetObject("TWOMAX_ESPACEJEUX_HAND_VALUE_THREE_RED_BMP", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap TWOMAX_ESPACEJEUX_HAND_VALUE_TWO_BLACK_BMP {
            get {
                object obj = ResourceManager.GetObject("TWOMAX_ESPACEJEUX_HAND_VALUE_TWO_BLACK_BMP", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap TWOMAX_ESPACEJEUX_HAND_VALUE_TWO_RED_BMP {
            get {
                object obj = ResourceManager.GetObject("TWOMAX_ESPACEJEUX_HAND_VALUE_TWO_RED_BMP", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap TWOMAX_ESPACEJEUX_PLAYER_0_DEALER_BMP {
            get {
                object obj = ResourceManager.GetObject("TWOMAX_ESPACEJEUX_PLAYER_0_DEALER_BMP", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap TWOMAX_ESPACEJEUX_PLAYER_1_TURN_INDICATOR_BMP {
            get {
                object obj = ResourceManager.GetObject("TWOMAX_ESPACEJEUX_PLAYER_1_TURN_INDICATOR_BMP", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap TWOMAX_ESPACEJEUX_PLAYER_EMPTY_BMP1 {
            get {
                object obj = ResourceManager.GetObject("TWOMAX_ESPACEJEUX_PLAYER_EMPTY_BMP1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap TWOMAX_ESPACEJEUX_PLAYER_EMPTY_BMP2 {
            get {
                object obj = ResourceManager.GetObject("TWOMAX_ESPACEJEUX_PLAYER_EMPTY_BMP2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap TWOMAX_ESPACEJEUX_STACK_VALUE_EIGHT_BMP {
            get {
                object obj = ResourceManager.GetObject("TWOMAX_ESPACEJEUX_STACK_VALUE_EIGHT_BMP", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap TWOMAX_ESPACEJEUX_STACK_VALUE_FIVE_BMP {
            get {
                object obj = ResourceManager.GetObject("TWOMAX_ESPACEJEUX_STACK_VALUE_FIVE_BMP", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap TWOMAX_ESPACEJEUX_STACK_VALUE_FOUR_BMP {
            get {
                object obj = ResourceManager.GetObject("TWOMAX_ESPACEJEUX_STACK_VALUE_FOUR_BMP", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap TWOMAX_ESPACEJEUX_STACK_VALUE_NINE_BMP {
            get {
                object obj = ResourceManager.GetObject("TWOMAX_ESPACEJEUX_STACK_VALUE_NINE_BMP", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap TWOMAX_ESPACEJEUX_STACK_VALUE_ONE_BMP {
            get {
                object obj = ResourceManager.GetObject("TWOMAX_ESPACEJEUX_STACK_VALUE_ONE_BMP", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap TWOMAX_ESPACEJEUX_STACK_VALUE_SEVEN_BMP {
            get {
                object obj = ResourceManager.GetObject("TWOMAX_ESPACEJEUX_STACK_VALUE_SEVEN_BMP", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap TWOMAX_ESPACEJEUX_STACK_VALUE_SIX_BMP {
            get {
                object obj = ResourceManager.GetObject("TWOMAX_ESPACEJEUX_STACK_VALUE_SIX_BMP", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap TWOMAX_ESPACEJEUX_STACK_VALUE_THREE_BMP {
            get {
                object obj = ResourceManager.GetObject("TWOMAX_ESPACEJEUX_STACK_VALUE_THREE_BMP", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap TWOMAX_ESPACEJEUX_STACK_VALUE_TWO_BMP {
            get {
                object obj = ResourceManager.GetObject("TWOMAX_ESPACEJEUX_STACK_VALUE_TWO_BMP", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap TWOMAX_ESPACEJEUX_STACK_VALUE_ZERO_BMP {
            get {
                object obj = ResourceManager.GetObject("TWOMAX_ESPACEJEUX_STACK_VALUE_ZERO_BMP", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap TWOMAX_ESPACEJEUX_TABLE_POT_VALUE_0_BMP {
            get {
                object obj = ResourceManager.GetObject("TWOMAX_ESPACEJEUX_TABLE_POT_VALUE_0_BMP", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap TWOMAX_ESPACEJEUX_TABLE_POT_VALUE_1_BMP {
            get {
                object obj = ResourceManager.GetObject("TWOMAX_ESPACEJEUX_TABLE_POT_VALUE_1_BMP", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap TWOMAX_ESPACEJEUX_TABLE_POT_VALUE_2_BMP {
            get {
                object obj = ResourceManager.GetObject("TWOMAX_ESPACEJEUX_TABLE_POT_VALUE_2_BMP", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap TWOMAX_ESPACEJEUX_TABLE_POT_VALUE_3_BMP2 {
            get {
                object obj = ResourceManager.GetObject("TWOMAX_ESPACEJEUX_TABLE_POT_VALUE_3_BMP2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap TWOMAX_ESPACEJEUX_TABLE_POT_VALUE_3_BMP3 {
            get {
                object obj = ResourceManager.GetObject("TWOMAX_ESPACEJEUX_TABLE_POT_VALUE_3_BMP3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap TWOMAX_ESPACEJEUX_TABLE_POT_VALUE_4_BMP {
            get {
                object obj = ResourceManager.GetObject("TWOMAX_ESPACEJEUX_TABLE_POT_VALUE_4_BMP", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap TWOMAX_ESPACEJEUX_TABLE_POT_VALUE_5_BMP {
            get {
                object obj = ResourceManager.GetObject("TWOMAX_ESPACEJEUX_TABLE_POT_VALUE_5_BMP", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap TWOMAX_ESPACEJEUX_TABLE_POT_VALUE_6_BMP {
            get {
                object obj = ResourceManager.GetObject("TWOMAX_ESPACEJEUX_TABLE_POT_VALUE_6_BMP", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap TWOMAX_ESPACEJEUX_TABLE_POT_VALUE_7_BMP {
            get {
                object obj = ResourceManager.GetObject("TWOMAX_ESPACEJEUX_TABLE_POT_VALUE_7_BMP", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap TWOMAX_ESPACEJEUX_TABLE_POT_VALUE_8_BMP {
            get {
                object obj = ResourceManager.GetObject("TWOMAX_ESPACEJEUX_TABLE_POT_VALUE_8_BMP", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap TWOMAX_ESPACEJEUX_TABLE_POT_VALUE_9_BMP {
            get {
                object obj = ResourceManager.GetObject("TWOMAX_ESPACEJEUX_TABLE_POT_VALUE_9_BMP", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap TWOMAX_ESPACEJEUX_TABLE_POT_VALUE_9_BMP2 {
            get {
                object obj = ResourceManager.GetObject("TWOMAX_ESPACEJEUX_TABLE_POT_VALUE_9_BMP2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap TWOMAX_ESPACEJEUX_TABLE_POT_VALUE_DOT_BMP {
            get {
                object obj = ResourceManager.GetObject("TWOMAX_ESPACEJEUX_TABLE_POT_VALUE_DOT_BMP", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap TWOMAX_ESPACEJEUX_TABLE_POT_VALUE_DOT_BMP2 {
            get {
                object obj = ResourceManager.GetObject("TWOMAX_ESPACEJEUX_TABLE_POT_VALUE_DOT_BMP2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap TWOMAX_ESPACEJEUX_TXT_RAISE_BMP {
            get {
                object obj = ResourceManager.GetObject("TWOMAX_ESPACEJEUX_TXT_RAISE_BMP", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
