/************************************
*****GENERATED BY BOTIMAGEHELPER*****
************************************/
namespace HEADS_UP
{
	 
	 public static class HEADS_UP_CONSTANTS_TEMPLATE
	 {
		#region HAND_CARD1_VALUE
		public const int HAND_CARD1_VALUE_X = 525;
		public const int HAND_CARD1_VALUE_Y = 240;
		public const int HAND_CARD1_VALUE_WIDTH = 13;
		public const int HAND_CARD1_VALUE_HEIGHT = 13;
		#endregion
		
		#region HAND_CARD1_SIGN
		public const int HAND_CARD1_SIGN_X = 525;
		public const int HAND_CARD1_SIGN_Y = 253;
		public const int HAND_CARD1_SIGN_WIDTH = 13;
		public const int HAND_CARD1_SIGN_HEIGHT = 13;
		#endregion
		
		#region HAND_CARD2_VALUE
		public const int HAND_CARD2_VALUE_X = 541;
		public const int HAND_CARD2_VALUE_Y = 240;
		public const int HAND_CARD2_VALUE_WIDTH = 13;
		public const int HAND_CARD2_VALUE_HEIGHT = 13;
		#endregion
		
		#region HAND_CARD2_SIGN
		public const int HAND_CARD2_SIGN_X = 541;
		public const int HAND_CARD2_SIGN_Y = 253;
		public const int HAND_CARD2_SIGN_WIDTH = 13;
		public const int HAND_CARD2_SIGN_HEIGHT = 13;
		#endregion
		
		#region HERO_DEALER
		public const int HERO_DEALER_X = 491;
		public const int HERO_DEALER_Y = 288;
		public const int HERO_DEALER_WIDTH = 10;
		public const int HERO_DEALER_HEIGHT = 10;
		#endregion
		
		#region VILAIN_DEALER
		public const int VILAIN_DEALER_X = 141;
		public const int VILAIN_DEALER_Y = 289;
		public const int VILAIN_DEALER_WIDTH = 10;
		public const int VILAIN_DEALER_HEIGHT = 10;
		#endregion
		
		#region VILAIN_STACK
		public const int VILAIN_STACK_X = 68;
		public const int VILAIN_STACK_Y = 319;
		public const int VILAIN_STACK_WIDTH = 45;
		public const int VILAIN_STACK_HEIGHT = 8;
		#endregion
		
		#region VILAIN_BET
		public const int VILAIN_BET_X = 316;
		public const int VILAIN_BET_Y = 199;
		public const int VILAIN_BET_WIDTH = 100;
		public const int VILAIN_BET_HEIGHT = 15;
		#endregion
		
		#region VILAIN_NAME
		public const int VILAIN_NAME_X = 63;
		public const int VILAIN_NAME_Y = 308;
		public const int VILAIN_NAME_WIDTH = 55;
		public const int VILAIN_NAME_HEIGHT = 10;
		#endregion
		
		#region HERO_TURN_INDICATOR
		public const int HERO_TURN_INDICATOR_X = 529;
		public const int HERO_TURN_INDICATOR_Y = 272;
		public const int HERO_TURN_INDICATOR_WIDTH = 14;
		public const int HERO_TURN_INDICATOR_HEIGHT = 14;
		#endregion
		
		#region BOARD_CARD1_VALUE
		public const int BOARD_CARD1_VALUE_X = 209;
		public const int BOARD_CARD1_VALUE_Y = 139;
		public const int BOARD_CARD1_VALUE_WIDTH = 15;
		public const int BOARD_CARD1_VALUE_HEIGHT = 15;
		#endregion
		
		#region BOARD_CARD2_VALUE
		public const int BOARD_CARD2_VALUE_X = 254;
		public const int BOARD_CARD2_VALUE_Y = 139;
		public const int BOARD_CARD2_VALUE_WIDTH = 15;
		public const int BOARD_CARD2_VALUE_HEIGHT = 15;
		#endregion
		
		#region BOARD_CARD3_VALUE
		public const int BOARD_CARD3_VALUE_X = 299;
		public const int BOARD_CARD3_VALUE_Y = 139;
		public const int BOARD_CARD3_VALUE_WIDTH = 15;
		public const int BOARD_CARD3_VALUE_HEIGHT = 15;
		#endregion
		
		#region BOARD_CARD4_VALUE
		public const int BOARD_CARD4_VALUE_X = 344;
		public const int BOARD_CARD4_VALUE_Y = 139;
		public const int BOARD_CARD4_VALUE_WIDTH = 15;
		public const int BOARD_CARD4_VALUE_HEIGHT = 15;
		#endregion
		
		#region BOARD_CARD5_VALUE
		public const int BOARD_CARD5_VALUE_X = 389;
		public const int BOARD_CARD5_VALUE_Y = 139;
		public const int BOARD_CARD5_VALUE_WIDTH = 15;
		public const int BOARD_CARD5_VALUE_HEIGHT = 15;
		#endregion
		
		#region BOARD_CARD1_SIGN
		public const int BOARD_CARD1_SIGN_X = 208;
		public const int BOARD_CARD1_SIGN_Y = 155;
		public const int BOARD_CARD1_SIGN_WIDTH = 15;
		public const int BOARD_CARD1_SIGN_HEIGHT = 15;
		#endregion
		
		#region BOARD_CARD2_SIGN
		public const int BOARD_CARD2_SIGN_X = 253;
		public const int BOARD_CARD2_SIGN_Y = 155;
		public const int BOARD_CARD2_SIGN_WIDTH = 15;
		public const int BOARD_CARD2_SIGN_HEIGHT = 15;
		#endregion
		
		#region BOARD_CARD3_SIGN
		public const int BOARD_CARD3_SIGN_X = 299;
		public const int BOARD_CARD3_SIGN_Y = 155;
		public const int BOARD_CARD3_SIGN_WIDTH = 15;
		public const int BOARD_CARD3_SIGN_HEIGHT = 15;
		#endregion
		
		#region BOARD_CARD4_SIGN
		public const int BOARD_CARD4_SIGN_X = 343;
		public const int BOARD_CARD4_SIGN_Y = 155;
		public const int BOARD_CARD4_SIGN_WIDTH = 15;
		public const int BOARD_CARD4_SIGN_HEIGHT = 15;
		#endregion
		
		#region BOARD_CARD5_SIGN
		public const int BOARD_CARD5_SIGN_X = 389;
		public const int BOARD_CARD5_SIGN_Y = 155;
		public const int BOARD_CARD5_SIGN_WIDTH = 15;
		public const int BOARD_CARD5_SIGN_HEIGHT = 15;
		#endregion
		
		
	 }
	 
}























































