/************************************
*****GENERATED BY BOTIMAGEHELPER*****
************************************/
namespace EMPTY_CONSTANTS
{
	 
	 public static class EMPTY_CONSTANTS
    {
		
	 }
	 
}